# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utility.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='utility.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rutility.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\".\n\x0cNumberDouble\x12\x0e\n\x06value1\x18\x01 \x01(\x02\x12\x0e\n\x06value2\x18\x02 \x01(\x02\x32\xbe\x01\n\nCalculator\x12\"\n\x06\x41\x64\x64Num\x12\r.NumberDouble\x1a\x07.Number\"\x00\x12\"\n\x06SubNum\x12\r.NumberDouble\x1a\x07.Number\"\x00\x12\"\n\x06MulNum\x12\r.NumberDouble\x1a\x07.Number\"\x00\x12\"\n\x06\x44ivNum\x12\r.NumberDouble\x1a\x07.Number\"\x00\x12 \n\nSquareRoot\x12\x07.Number\x1a\x07.Number\"\x00\x62\x06proto3')
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Number.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=40,
)


_NUMBERDOUBLE = _descriptor.Descriptor(
  name='NumberDouble',
  full_name='NumberDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value1', full_name='NumberDouble.value1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value2', full_name='NumberDouble.value2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['NumberDouble'] = _NUMBERDOUBLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'utility_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  ))
_sym_db.RegisterMessage(Number)

NumberDouble = _reflection.GeneratedProtocolMessageType('NumberDouble', (_message.Message,), dict(
  DESCRIPTOR = _NUMBERDOUBLE,
  __module__ = 'utility_pb2'
  # @@protoc_insertion_point(class_scope:NumberDouble)
  ))
_sym_db.RegisterMessage(NumberDouble)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=91,
  serialized_end=281,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddNum',
    full_name='Calculator.AddNum',
    index=0,
    containing_service=None,
    input_type=_NUMBERDOUBLE,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubNum',
    full_name='Calculator.SubNum',
    index=1,
    containing_service=None,
    input_type=_NUMBERDOUBLE,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MulNum',
    full_name='Calculator.MulNum',
    index=2,
    containing_service=None,
    input_type=_NUMBERDOUBLE,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DivNum',
    full_name='Calculator.DivNum',
    index=3,
    containing_service=None,
    input_type=_NUMBERDOUBLE,
    output_type=_NUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SquareRoot',
    full_name='Calculator.SquareRoot',
    index=4,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
